#!/bin/sh

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev

echo ""
echo "================================="
echo " Welcome to Neytra OS 2026"
echo "================================="
echo ""

# Handle shutdown signals
trap "poweroff -f" SIGTERM SIGPWR

/bin/sh