#!/bin/sh

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev

printf '\n'
printf '\033[1;36m%s\033[0m\n' \
  ' _   _ ________     _________ _____               ____   _____ ' \
  '| \ | |  ____\ \   / /__   __|  __ \     /\      / __ \ / ____|' \
  '|  \| | |__   \ \_/ /   | |  | |__) |   /  \    | |  | | (___  ' \
  '| . ` |  __|   \   /    | |  |  _  /   / /\ \   | |  | |\___ \ ' \
  '| |\  | |____   | |     | |  | | \ \  / ____ \  | |__| |____) |' \
  '|_| \_|______|  |_|     |_|  |_|  \_\/_/    \_\  \____/|_____/ '
  printf '\n'
printf '\033[1;33m              >> Neytra OS 2026 <<\033[0m\n'
printf '\033[1;35m              Author: @thedeveloperyug\033[0m\n'
printf '\n'

# Handle shutdown signals
trap "poweroff -f" SIGTERM SIGPWR

/bin/sh